name: "welcome-new-contributors"
description: "Greet new contributors with a welcome message when they open a new issue/PR."
author: 'garg3133'
inputs:
  token:
    description: 'The GITHUB_TOKEN to access your repository or OAUTH_TOKEN to use your bot github account.'
    required: true
  is-oauth-token:
    description: 'Is the token provided above an OAUTH_TOKEN? (Bot account should be a collaborator on your repo.)'
    required: false
    default: false
  issue-message:
    description: 'Welcome message for new issue.'
    required: false
  pr-message:
    description: 'Welcome message for new issue.'
    required: false
runs:
  using: 'node20'
  main: 'dist/index.js'
